version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Build and push docker"
          command: |
            cp Dockerfile.production Dockerfile
            docker build -t chatchaisi/node-exam:latest .
            docker build -t chatchaisi/node-exam:${CIRCLE_SHA1} .
            docker push chatchaisi/node-exam:latest
            docker push chatchaisi/node-exam:${CIRCLE_SHA1}
      - run:
          name: "Deploy to rancher"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
              etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
              --imageUuid 'docker:chatchaisi/node-exam:latest'\
              --batch_size 3 --start_first \
              --auto_complete --timeout 600 \
              /
      - run: echo DONE
